### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.


In [2]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [3]:
import numpy as np

In [74]:
array=np.random.randint(20, size=(5,5))
array[0:5,2:3]=1 
print(array)

[[ 1  1  1  7  9]
 [ 7 13  1  7  0]
 [ 7  4  1 11  4]
 [ 7  4  1 13 18]
 [ 2  9  1 19 15]]


In [58]:
array=np.arange(1,17,1).reshape(4,4)
np.fill_diagonal(array,0)
print(array)

[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [95]:
arr2=np.arange(1,37,1).reshape(6,6)
print(arr2)
sub_array=arr2[2:5,1:4]
print(sub_array)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[14 15 16]
 [20 21 22]
 [26 27 28]]


In [122]:
arr3=np.random.randint(25,size=(5,5))
print(arr3)
top    = arr3[0, :]
bottom = arr3[-1, :]
left   = arr3[1:-1, 0]
right  = arr3[1:-1, -1]
border=np.concatenate((top,right,bottom,left))
print(border)

[[24  5 11 13 17]
 [15  2 17  4  2]
 [ 2 18  1 22 19]
 [10  8 17 10 15]
 [18  9  8 16 23]]
[24  5 11 13 17  2 19 15 18  9  8 16 23 15  2 10]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [126]:
arr1=np.random.randint(12,size=(3,4))
print(arr1)
arr2=np.random.randint(12,size=(3,4))
print(arr2)

print("Addition:", arr1+arr2)
print("Subtraction:", arr1-arr2)
print("Multiplication", arr1*arr2)
print("Division:", arr1/arr2)


[[10  1  9  3]
 [ 3  9  6  1]
 [ 5  1  4  8]]
[[ 5  9 11 11]
 [ 5  7  4  4]
 [ 1 10 11  4]]
Addition: [[15 10 20 14]
 [ 8 16 10  5]
 [ 6 11 15 12]]
Subtraction: [[ 5 -8 -2 -8]
 [-2  2  2 -3]
 [ 4 -9 -7  4]]
Multiplication [[50  9 99 33]
 [15 63 24  4]
 [ 5 10 44 32]]
Division: [[2.         0.11111111 0.81818182 0.27272727]
 [0.6        1.28571429 1.5        0.25      ]
 [5.         0.1        0.36363636 2.        ]]


In [130]:
arr1=np.arange(1,17,1).reshape(4,4)
print(arr1)
row_sum=np.sum(arr1,axis=0)
column_sum=np.sum(arr1,axis=1)
print(row_sum)
print(column_sum)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[28 32 36 40]
[10 26 42 58]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [134]:
arr1= np.random.randint(25,size=(5,5))
print(arr1)
print("mean:",np.mean(arr1))
print("median:",np.median(arr1))
print("standard deviation:",np.std(arr1))
print("variance:",np.var(arr1))

[[18  7 22  1 19]
 [24 12 19 19 24]
 [23 23  5 15  3]
 [ 1  4  6  0 11]
 [ 0  8  8 18  0]]
mean: 11.6
median: 11.0
standard deviation: 8.522910301065007
variance: 72.64


In [137]:
arr1=np.arange(1,10,1).reshape(3,3)
print(arr1)
mean=np.mean(arr1)
std_dev=np.std(arr1)
normalised_data=(arr1-mean)/std_dev
print("Normalised Data:",normalised_data)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalised Data: [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [140]:
arr1=np.random.randint(9, size=(3,3))
print(arr1)
arr2=np.random.randint(3, size=(3,))
print(arr2)

result=arr1+arr2
print("Result:", result)

[[4 5 7]
 [5 7 6]
 [4 3 2]]
[1 1 0]
Result: [[5 6 7]
 [6 8 6]
 [5 4 2]]


In [149]:
arr1=np.random.randint(16, size=(4,4))
print(arr1)
arr2=np.random.randint(4, size=(4,))
print(arr2)
result=arr1-arr2.reshape(4,1)
print("Result:",result)

[[12 10 14  8]
 [ 0  1  1 13]
 [ 4  7  7  2]
 [ 8 12 14 15]]
[2 3 3 3]
Result: [[10  8 12  6]
 [-3 -2 -2 10]
 [ 1  4  4 -1]
 [ 5  9 11 12]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [153]:
arr1=np.random.randint(9, size=(3,3))
print(arr1)
print("Determinant:", np.linalg.det(arr1))
print("Inverse:", np.linalg.inv(arr1))
print("Eigen Values:", np.linalg.eig(arr1))

[[8 8 8]
 [0 7 0]
 [6 6 8]]
Determinant: 111.99999999999996
Inverse: [[ 0.5        -0.14285714 -0.5       ]
 [ 0.          0.14285714  0.        ]
 [-0.375       0.          0.5       ]]
Eigen Values: EigResult(eigenvalues=array([14.92820323,  1.07179677,  7.        ]), eigenvectors=array([[ 0.75592895, -0.75592895, -0.53581574],
       [ 0.        ,  0.        ,  0.6295835 ],
       [ 0.65465367,  0.65465367, -0.56260653]]))


In [157]:
arr1=np.random.randint(6, size=(2,3))
arr2=np.random.randint(6, size=(3,2))
print(arr1)
print(arr2)
result= arr1 @ arr2
print(result)

[[3 3 3]
 [0 3 1]]
[[0 5]
 [1 1]
 [3 1]]
[[12 21]
 [ 6  4]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [161]:
arr1=np.arange(1,10,1).reshape(3,3)
print(arr1)
arr2=arr1.reshape(1,9)
print(arr2)
arr3=arr2.reshape(9,1)
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [167]:
arr1=np.random.randint(25, size=(5,5))
print(arr1)
arr2=arr1.flatten()
print(arr2)
arr3=arr2.reshape(5,5)
print(arr3)

[[13 13  3 14 13]
 [17 10 13  6 10]
 [ 1 16  8 18  7]
 [22  7  8  1  8]
 [21 16 18 23 10]]
[13 13  3 14 13 17 10 13  6 10  1 16  8 18  7 22  7  8  1  8 21 16 18 23
 10]
[[13 13  3 14 13]
 [17 10 13  6 10]
 [ 1 16  8 18  7]
 [22  7  8  1  8]
 [21 16 18 23 10]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [172]:
arr1=np.random.randint(25, size=(5,5))
print(arr1)
print (arr1[[0, 0, 4, 4], [0, 4, 0, 4]])

[[24 22 14 18 14]
 [ 9 12  2  1 12]
 [12  2 15  2  7]
 [ 5 21 16 21 20]
 [ 5 24 18 13 16]]
[24 14  5 16]


In [174]:
arr1=np.random.randint(16, size=(4,4))
print(arr1)
arr1[arr1>10]=10
print(arr1)

[[11  4 11  0]
 [ 3  3 14  8]
 [15  1 12  6]
 [15  3  0 14]]
[[10  4 10  0]
 [ 3  3 10  8]
 [10  1 10  6]
 [10  3  0 10]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [ ]:
data_type=[('name','U10'),('age','i4'),('weight','f4')]
data=np.array([('Udai',22,50),('Jini',21,43),('Bhai',22,1000)], dtype=data_type)
print(data_type)
print(data)

sorted_data=np.sort(data, order="age")
print("sorted data:", sorted_data)

[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
[('Udai', 22,   50.) ('Jini', 21,   43.) ('Bhai', 22, 1000.)]
sorted data: [('Jini', 21,   43.) ('Bhai', 22, 1000.) ('Udai', 22,   50.)]


In [11]:
data_type=[('x','i4'),('y','i4')]
data=np.array([(10,20),(15,34),(14,24)],dtype=data_type)

distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances:")
print(distances)

Euclidean distances:
[[ 0.         14.86606875  5.65685425]
 [14.86606875  0.         10.04987562]
 [ 5.65685425 10.04987562  0.        ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [14]:
import numpy.ma as ma

array = np.random.randint(1, 21, size=(4, 4))
masked_array = ma.masked_greater(array, 10)
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

sum_unmasked = masked_array.sum()
print("Sum of unmasked elements:", sum_unmasked)

Original array:
[[10  6 11  9]
 [11  8 10 13]
 [13 11 18 14]
 [14  1 11 15]]
Masked array:
[[10 6 -- 9]
 [-- 8 10 --]
 [-- -- -- --]
 [-- 1 -- --]]
Sum of unmasked elements: 44


In [15]:
array = np.random.randint(1, 21, size=(3, 3))
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)


mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:")
print(masked_array)

Original array:
[[ 6 11 20]
 [ 2 13  4]
 [ 4 13 10]]
Masked array:
[[-- 11 20]
 [2 -- 4]
 [4 13 --]]
Modified masked array:
[[ 9 11 20]
 [ 2  9  4]
 [ 4 13  9]]
